name: s3-logs-sync

on:
  workflow_dispatch:
    inputs:
      environment:
        description: "実行対象の環境を'stg'または'prd'で入力"
        required: true
      job:
        description: "S3への同期処理の場合は'sync'でログファイルの削除は'del'を入力"
        required: true

env:
  STG_HOST: 10.10.10.10
  PRD_HOST: 10.10.10.11
  STG_DIST_BACKET:
  PRD_DIST_BACKET:

jobs:
  stg-job:
    if: ${{ github.event.inputs.environment == 'stg' }}
    runs-on: self-hosted
    steps:
      - if: ${{ github.event.inputs.job == 'sync' }}
        run: |
          cd "なんのディレクトリ？"
          echo "${{ secrets.ANSIBLE_VAULT_PASSWORD }}" > ./vault_password_file
          echo "${{ secrets.ANSIBLE_SSH_PRIVATE_KEY_STG }}" > ./id_rsa
          chmod 600 ./id_rsa
          ansible ${{ env.STG_HOST }} aws s3 sync "転送元DIR" s3://${{ env.STG_DIST_BACKET }}
      - if: ${{ github.event.inputs.job == 'del' }}
        run: |
          cd "なんのディレクトリ？"
          echo "${{ secrets.ANSIBLE_VAULT_PASSWORD }}" > ./vault_password_file
          echo "${{ secrets.ANSIBLE_SSH_PRIVATE_KEY_STG }}" > ./id_rsa
          chmod 600 ./id_rsa
          ansible ${{ env.STG_HOST }} find ./ -mtime +50 -name | xargs rm -f

  prd-job:
    if: ${{ github.event.inputs.environment == 'prd' }}
    runs-on: self-hosted
    steps:
      - if: ${{ github.event.inputs.job == 'sync' }}
        run: |
          cd "なんのディレクトリ？"
          echo "${{ secrets.ANSIBLE_VAULT_PASSWORD }}" > ./vault_password_file
          echo "${{ secrets.ANSIBLE_SSH_PRIVATE_KEY_STG }}" > ./id_rsa
          chmod 600 ./id_rsa
          ansible ${{ env.PRD_HOST }} aws s3 sync "転送元DIR" s3://${{ env.PRD_DIST_BACKET }}
      - if: ${{ github.event.inputs.job == 'del' }}
        run: |
          cd "なんのディレクトリ？"
          echo "${{ secrets.ANSIBLE_VAULT_PASSWORD }}" > ./vault_password_file
          echo "${{ secrets.ANSIBLE_SSH_PRIVATE_KEY_STG }}" > ./id_rsa
          chmod 600 ./id_rsa
          ansible ${{ env.PRD_HOST }} find ./ -mtime +50 -name | xargs rm -f